"""Constantes da integração PT Energy Consumption Sensor."""

DOMAIN = "pt_energy_consumption_sensor"

# --- Chaves de configuração -------------------------------------------------
# Mantidas em camelCase por compatibilidade com instalações existentes.
CONF_STATISTIC_ID = "statistic_id"
CONF_DIA_INICIO_FATURACAO = "diaInicioFaturacao"
CONF_OPCAO_TARIFARIA = "opcaoTarifaria"
CONF_CICLO_HORARIO = "cicloHorario"
CONF_REGIAO = "regiao"
CONF_POTENCIA_CONTRATADA = "potenciaContratada"
CONF_FAMILIAS_NUMEROSAS = "familiasNumerosas"
CONF_CUSTO_ENERGIA_DIA = "custoEnergiaDia"
CONF_CUSTO_ENERGIA_KWH = "custoEnergiaKwh"
CONF_CUSTO_VAZIO_KWH = "custoVazioKwh"
CONF_CUSTO_FORA_VAZIO_KWH = "custoForaVazioKwh"
CONF_CUSTO_CHEIO_KWH = "custoCheioKwh"
CONF_CUSTO_PONTA_KWH = "custoPontaKwh"
CONF_CUSTO_TARIFA_SOCIAL_KWH = "custoTarifaSocialKwh"
CONF_CUSTO_IEC_KWH = "custoIECKwh"
CONF_CUSTO_AUDIOVISUAL = "custoAudiovisual"
CONF_CUSTO_DGEG = "custoDGEG"

# --- Valores por defeito ----------------------------------------------------
# O sensor de consumo é escolhido pelo utilizador na configuração (sem default),
# para não impor nenhum dispositivo específico nem expor identificadores pessoais.
DEFAULT_STATISTIC_ID = ""
DEFAULT_DIA_INICIO_FATURACAO = 11
DEFAULT_OPCAO_TARIFARIA = "simples"
DEFAULT_CICLO_HORARIO = "diario"
DEFAULT_REGIAO = "continente"
DEFAULT_POTENCIA_CONTRATADA = 6.9
DEFAULT_FAMILIAS_NUMEROSAS = False
DEFAULT_CUSTO_ENERGIA_DIA = 0.4624
DEFAULT_CUSTO_ENERGIA_KWH = 0.1337
DEFAULT_CUSTO_VAZIO_KWH = 0.0
DEFAULT_CUSTO_FORA_VAZIO_KWH = 0.0
DEFAULT_CUSTO_CHEIO_KWH = 0.0
DEFAULT_CUSTO_PONTA_KWH = 0.0
DEFAULT_CUSTO_TARIFA_SOCIAL_KWH = 0.0017
DEFAULT_CUSTO_IEC_KWH = 0.0010
DEFAULT_CUSTO_AUDIOVISUAL = 2.85
DEFAULT_CUSTO_DGEG = 0.07

DEFAULTS: dict[str, object] = {
    CONF_STATISTIC_ID: DEFAULT_STATISTIC_ID,
    CONF_DIA_INICIO_FATURACAO: DEFAULT_DIA_INICIO_FATURACAO,
    CONF_OPCAO_TARIFARIA: DEFAULT_OPCAO_TARIFARIA,
    CONF_CICLO_HORARIO: DEFAULT_CICLO_HORARIO,
    CONF_REGIAO: DEFAULT_REGIAO,
    CONF_POTENCIA_CONTRATADA: DEFAULT_POTENCIA_CONTRATADA,
    CONF_FAMILIAS_NUMEROSAS: DEFAULT_FAMILIAS_NUMEROSAS,
    CONF_CUSTO_ENERGIA_DIA: DEFAULT_CUSTO_ENERGIA_DIA,
    CONF_CUSTO_ENERGIA_KWH: DEFAULT_CUSTO_ENERGIA_KWH,
    CONF_CUSTO_VAZIO_KWH: DEFAULT_CUSTO_VAZIO_KWH,
    CONF_CUSTO_FORA_VAZIO_KWH: DEFAULT_CUSTO_FORA_VAZIO_KWH,
    CONF_CUSTO_CHEIO_KWH: DEFAULT_CUSTO_CHEIO_KWH,
    CONF_CUSTO_PONTA_KWH: DEFAULT_CUSTO_PONTA_KWH,
    CONF_CUSTO_TARIFA_SOCIAL_KWH: DEFAULT_CUSTO_TARIFA_SOCIAL_KWH,
    CONF_CUSTO_IEC_KWH: DEFAULT_CUSTO_IEC_KWH,
    CONF_CUSTO_AUDIOVISUAL: DEFAULT_CUSTO_AUDIOVISUAL,
    CONF_CUSTO_DGEG: DEFAULT_CUSTO_DGEG,
}
